site_name: "Matech Studios - Playbook: Recipes Recommender" 
site_url: https://github.com/Matech-Studios/tech_docs/
site_author: "Matech Studios"
copyright: Copyright &copy; 2020 - 2021 Matech Studios
site_url: https://github.com/Matech-Studios

theme:
    name: material

    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Matech logo
    logo: img/matech.png
    favicon: img/matech.png

    # Font
    font:
      text: Roboto

    # Navigation
    features:
      # - navigation.sections
      - navigation.instant
      - navigation.tabs
      - navigation.top
      - toc.integrate

# Features about format
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Added plugins
plugins:
  - search

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Matech-Studios
  version:
    provider: mike

# Structure
pages:
- Home: 'README.md'
- Contents:
    - 'Preface': '0_preface.md'
    - 'Chapter 1: Understanding': '1_understanding.md'
    - 'Chapter 2: Preparation': '2_preparation.md'
    - 'Chapter 3: Execution': '3_execution.md'
    - 'Chapter 4: Acceptance': '4_acceptance.md'
    - 'Epilogue': '5_epilogue.md'
- How-To Guides:
    - 'Poll to Collect Requirements': 'how-to/poll_requirements.md'
    - 'Data Quality Control': 'how-to/data_quality_control.md'
    - 'Asynchronous Service with aio-pika': 'how-to/service_aio-pika.md'
