name: Build Github Page
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: playbook_docs

      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.7' 
      
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install mkdocs-material 

      - name: Deploy 
        run: | 
          git pull 
          git checkout playbook_docs
          mkdocs gh-deploy 